# Permalinks
permalink:           pretty

# Setup
title:               Keith Kirkpatrick
tagline:             A Personal Data Science Blog
url:                 http://keith12345.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Keith Kirkpatrick
  url:               https://www.linkedin.com/in/keith-kirkpatrick/
  email:             keithmkirkpatrick@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/keith12345

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-slate
